### ISSUE TITLE
Comentários de UX

### ISSUE THREAD

**Issue by khamusa** [eufrankoficial/giphyapitest#2]
1. Ao recarregar a página ou fechar o browser e reabrir, perco meus favoritos, o que faz com que a funcionalidade seja pouco útil;
2. Na listagem de favoritos, o botão de favoritar ainda é exibido, e clicar dá uma mensagem de que o gif já é favorito. O ideal seria ocultar esse botão ou permitir a remoção do item como favorito;
3. Um mesmo gif adicionado como favorito continua exibindo o botão de favoritar quando navego para os favoritos e volto para a home;
4. Tem um gif no meu feed que vaza para fora do container: 
![Screenshot from 2020-10-23 14-25-42](https://user-images.githubusercontent.com/1708578/97034700-b0e54000-153b-11eb-80b8-0e5a2370af0b.png)
5. Não consigo buscar um gif apertando enter, tenho que explicitamente clicar no botão;
6. O fluxo do shuffle não ficou claro (demorei a entender que posso clicar na imagem e isso me navega para a interface onde teria o shuffle)
7. Quando faço o shuffle, o histórico do navegador não é salvo, o que faz com que eu não consiga voltar para as imagens precedentes ao clicar em voltar no navegador;
8. Percebi que o behavior do shuffle implementado foi de buscar itens relacionados utilizando o título do gif corrente como termo de busca: https://github.com/eufrankoficial/giphyapitest/blob/caccf33df1e371766579423198d12c6ca8690d02/src/pages/Gifs/Detail/index.js#L37
A ideia contudo era usar sempre o termo de busca que o usuário informou, como conversamos no e-mail de esclarecimento. 
O shuffle é uma funcionalidade que faz sentido à partir da busca textual do usuário. O que você implementou é mais o conceito de gifs relacionados a um determinado gif do que o conceito de shuffle (de fato, reparei que vc usou o termo related no código).
9. O uso de `alert` para comunicar o sucesso de algumas ações não ficou bom, a interface tem que ter formas interessantes de comunicar o resultado da interação do usuário.

**Comment by nullioxyz** [comment]
1. Poderia ter usado o storage do navegador para gravar os favoritos, seria mais saudável para a permanência dos dados.
2. Realmente, não tratei essa questão dos favoritos. Apenas tratei na hora de adicionar verificando se o mesmo já existe.
3. idem ao item anterior
4. Poderia ter colocado um tamanho padrão para todos os gifs, assim evitariamos esse tipo falha no layout.
5. Apenas coloquei no clique do botão, mas é uma pratica a ser implementada pois todos nós usamos o entender ao digitar alguma coisa em um input
6. Sobre o shuffle, provavelmente então eu tenha me equivocado na implementação. 
7. Não implementei a funcionalidade de voltar o gif.
8. idem ao item 6
9. Eu não me preocupei em melhorar essa questão do alerta. Realmente, deveria ter feito de uma forma mais amigável ao usuário.
