### ISSUE TITLE
Comentários gerais sobre o código

### ISSUE THREAD

**Issue by khamusa** [eufrankoficial/giphyapitest#3]
- Faltou atualizar o Readme. Não é nada crítico, mas demonstra pouca preocupação com a comunicação, e na nossa área uma boa comunicação é a base pra fazer um bom trabalho;
- Ficaram alguns console.log no código;
- O uso de `alert` para comunicar o sucesso de algumas ações não ficou bom, a interface tem que ter formas interessantes de comunicar o resultado da interação do usuário.
- Reparei que você não configurou o arquivo `.editorconfig` (se vc não conhece dê uma olhada https://editorconfig.org/). É interessante estabelecer os padrões de formatação do código desde o início (sugiro configurar o uso de espaços ao invés de tab também, assim você evita problemas de formatação de código entre plataformas ou editores que tratam tabs / espaços de formas diferentes)
- Achei interessante o uso de Context para os favoritos, mas como comentei no issue de ux, faltou pensar em armazenar os favoritos não só na memória do browser, para persitir entre sessões;
- O uso de linhas em branco não é consistente. Use linhas em branco para facilitar a leitura panorâmica do seu código. Uma linha em branco para separar conceitos não relacionados, mas nunca use mais de uma linha em branco entre blocos de código. Exemplo: https://github.com/eufrankoficial/giphyapitest/blob/main/src/contexts/FavoriteContext.js#L8
Dica: Sempre use o https://prettier.io/ em qualquer projeto
- Você fez bem em encapsular o acesso à api do giphy sob o conceito de `services`, mas acho que poderia ter feito mais encapsulamento dos detalhes da api. Um exemplo é esse aqui: https://github.com/eufrankoficial/giphyapitest/blob/main/src/pages/Home/index.js#L47
Esse componente da sua aplicação, que faz parte da camada de `view` precisa saber vários detalhes sobre como a api do giphy funciona. Ao invés disso, encapsule o acesso à api em funções que aceitem exatamente os parâmetros que seus usuários **precisam** saber. O componente não precisa saber por exemplo que é na rota `/trending` que a informação é obtida.
Exemplo de interface (pseudo-código):
```
const trendingGifs = fetchTrendingGifs(page, search_term)
```

Usando hooks dá pra fazer coisas ainda mais elegantes, tipo:

```
const { data, loading, error, fetchMore } = useTrendingGifs();

if (loading) return "Loading...";
if(error) return <SomeErrorStateComponent />;

return <GifsFeed data={data} fetchMore={fetchMore} />
```
Você pode criar essa interface usando um array hardcoded por exemplo, migrar para uma api REST depois ou para uma api GraphQl, implementar um mecanismo de caching intermediário, e os usuários dessa api não precisam nem saber que você está fazendo essas alterações. A função `fetchMore` abstrai completamente o conceito de paginação também. Interfaces definem barreiras de conhecimento que são saudáveis para nosso código. Há outras formas de obter esse tipo de abstração também, o uso do hook é só um exemplo.

**Comment by eufrankoficial** [comment]
Interessante sua a análise. Infelizmente não me preocupei com alguns conceitos por estar preocupado com o app funcionar como eu estava pensando que deveria. Como ReactJs é recente pra mim enquanto um estudante e usuário, ainda estou aprendendo alguns conceitos. 

* O .editorconfig eu não configurei e me lembrei de depois que mandei pra ti, e como já havia mandado o código final, pensei em não atualizar para que visse o código como te mandei e aguardar tua análise
* Fiquei na dúvida em usuar o storage pra poder armazenar os favoritos, fiquei com receio de isso não ser uma boa pratica, mas faz sentido o que tu disse, os dados precisam persistir.

**Comment by nullioxyz** [comment]
Interessante sua a análise. Infelizmente não me preocupei com alguns conceitos por estar preocupado com o app funcionar como eu estava pensando que deveria. Como ReactJs é recente pra mim enquanto um estudante e usuário, ainda estou aprendendo alguns conceitos.

- O .editorconfig eu não configurei e me lembrei de depois que mandei pra ti, e como já havia mandado o código final, pensei em não atualizar para que visse o código como te mandei e aguardar tua análise

- Fiquei na dúvida em usuar o storage pra poder armazenar os favoritos, fiquei com receio de isso não ser uma boa pratica, mas faz sentido o que tu disse, os dados precisam persistir de alguma forma.

- Eu revisei meu código final, e removi várias coisas que não estava utilizando, coisas são normais de colocar em momento de desenvolvimento e não serem necessárias depois, algumas coisas passaram batidas. Mas ficarei atento aos detalhes mencionados.

- Eu poderia encapsular várias coisas no projeto em si. Poderia ter deixado muito mais organizado as chamadas api, criar um arquivo que trata apenas disso, sem que eu precise explicitar isso diretamente no meu componente.
